### ISSUE TITLE
APK for testing

### ISSUE THREAD

**Issue by raphmim** [KirkBushman/zammad-android#1]
Hello, is there an APK to test this? I'd love to see what this looks like on Android, but I'm not technical enough to use Jitpack

**Comment by KirkBushman** [comment]
Hi, 
Jitpack is used for integrating the library in an Android project, if you want to test it out you could simply download the project as a zip and open it up with Android Studio.

The project contains a sample app, you can connect you phone or open an emulator and press Run to push the APK on device. Or you can got to Build > Build APK to generate one. It's going to ask for a URL of your Zammad server, username and password at the beginning.

Remember this library provides the Zammad API to use on Android, this could be used as a base for any Zammad app integration, including a full client. It provides a sample app but it's pretty barebone as it's used for testing purposes only. Don't expect a fully featured and cured application.

**Comment by raphmim** [comment]
Thank you Kirk, I'll try and follow your instructions to check it out!
