### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by astrugatch** [KirkBushman/zammad-android#3]
I am definitely interested in this project and app for our environment, but don't have any experience with mobile development. Would it be possible to update the Readme with more specifics about the required environment and process?

Thanks!

**Comment by KirkBushman** [comment]
I'm sure I can add a few examples of use in the README. The lines to add the library to gradle are already in there, I would suggest, if you are starting from zero, to lookup some tutorial about starting an app and app architecture like MVVM.

**Comment by KirkBushman** [comment]
I've updated the README with some info. You should look into the sample app for more.
